### ISSUE TITLE
RPI-Zero2W

### ISSUE THREAD

**Issue by RustyMan22** [romainreignier/minimal_raspberrypi_buildroot#6]
Do this repo support this board?

**Comment by romainreignier** [comment]
This repo has only been tested on a Raspberry Pi 3 and does not support the Zero 2W.
But the board is supported by mainline Buildroot: https://github.com/buildroot/buildroot/blob/07a03a8549b0e1ed92993311be337c7a382b6446/configs/raspberrypizero2w_defconfig
So this repo can help porting to the Zero 2W because the CPU are close.
PR is welcomed if you have a working configuration for the Zero 2W. I don't own this board so I cannot test it.
